/*
Guncel BIN LISTESI
FF : http://friendfeed.com/turkserpico
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `binlist`
-- ----------------------------
DROP TABLE IF EXISTS `binlist`;
CREATE TABLE `binlist` (
  `bin` int(11) NOT NULL DEFAULT '0',
  `banka_kodu` int(11) DEFAULT NULL,
  `banka_adi` varchar(100) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `sub_type` varchar(50) DEFAULT NULL,
  `virtual` varchar(50) DEFAULT NULL,
  `prepaid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`bin`),
  KEY `banka_kodu` (`banka_kodu`,`banka_adi`)
) ENGINE=InnoDB;

-- ----------------------------
-- Records of binlist
-- ----------------------------
INSERT INTO `binlist` VALUES ('413226', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('444676', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('444677', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('444678', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('453955', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('453956', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' GOLD', '', '');
INSERT INTO `binlist` VALUES ('454671', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('454672', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('454673', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('454674', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' GOLD', '', '');
INSERT INTO `binlist` VALUES ('454894', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'VISA', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540130', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540134', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'MASTERCARD', ' GOLD', '', '');
INSERT INTO `binlist` VALUES ('541001', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('541033', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'MASTERCARD', ' GOLD', '', '');
INSERT INTO `binlist` VALUES ('542374', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('547287', '10', 'T.C. ZİRAAT BANKASI A.Ş.', 'MASTERCARD', ' BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('415514', '12', 'T. HALK BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('492094', '12', 'T. HALK BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('492095', '12', 'T. HALK BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('498852', '12', 'T. HALK BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('521378', '12', 'T. HALK BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('540435', '12', 'T. HALK BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('543081', '12', 'T. HALK BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('552879', '12', 'T. HALK BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('510056', '12', 'T. HALK BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('402940', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('409084', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411724', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411942', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411943', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411944', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411979', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('415792', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('416757', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('428945', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('493840', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('493841', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('493846', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('520017', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540045', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('540046', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('542119', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('542798', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('542804', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('547244', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('552101', '15', 'T. VAKIFLAR BANKASI T.A.O.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('402458', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('402459', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('406015', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('427707', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('440247', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('440273', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('440293', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('440294', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('479227', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('489494', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('489495', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('489496', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('510138', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('510139', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('510221', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('512753', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('512803', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('524346', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('524839', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('524840', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('528920', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('530853', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('545124', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'SIGNIA', '', '');
INSERT INTO `binlist` VALUES ('553090', '32', 'TÜRK EKONOMİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('413252', '46', 'AKBANK T.A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('425669', '46', 'AKBANK T.A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('432071', '46', 'AKBANK T.A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('432072', '46', 'AKBANK T.A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('435508', '46', 'AKBANK T.A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('435509', '46', 'AKBANK T.A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('493837', '46', 'AKBANK T.A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('512754', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('520932', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('521807', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('524347', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('542110', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('552608', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('552609', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('553056', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('557113', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('557829', '46', 'AKBANK T.A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('403836', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('409622', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('411156', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411157', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('411158', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('411159', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('411160', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('433383', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('433384', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('494063', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('494064', '59', 'ŞEKERBANK T.A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('521394', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('521827', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('525404', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('530866', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('539703', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('547311', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('549208', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('549394', '59', 'ŞEKERBANK T.A.Ş.', 'MASTERCARD', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('403280', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('403666', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('404308', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('413836', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('426886', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('426887', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('426888', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('427314', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('427315', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('428220', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('428221', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('432154', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('448472', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('461668', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('462274', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('467293', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('467294', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('467295', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('474151', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('482489', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('482490', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('482491', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('486567', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('487074', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('487075', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('489478', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('490175', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('492186', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('492187', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('492193', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('493845', '62', 'T. GARANTİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('514915', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('520097', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('520922', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('520940', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('520988', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('521368', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('521824', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('521825', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('521832', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('522204', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('528939', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('528956', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('533169', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('534261', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'WORLD', '', '');
INSERT INTO `binlist` VALUES ('540036', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540037', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('540226', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540227', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540669', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540709', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('541865', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('542030', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('544078', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('545102', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'SIGNIA', '', '');
INSERT INTO `binlist` VALUES ('546001', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', null, 'PREPAID');
INSERT INTO `binlist` VALUES ('547302', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('552095', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('553130', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('554796', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('554960', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('557023', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('557945', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC ', 'virtual', '');
INSERT INTO `binlist` VALUES ('558699', '62', 'T. GARANTİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('418342', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('418343', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('418344', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('418345', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('450803', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('454318', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('454358', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('454359', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('454360', '64', 'T. İŞ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('510152', '64', 'T. İŞ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540667', '64', 'T. İŞ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540668', '64', 'T. İŞ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('543771', '64', 'T. İŞ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('552096', '64', 'T. İŞ BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('553058', '64', 'T. İŞ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('404809', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('446212', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('450634', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('455359', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('477959', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('479794', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('479795', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('491205', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('491206', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('492128', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('492130', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('492131', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('510054', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('540061', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540062', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('540063', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('540122', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540129', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', ' GOLD', '', '');
INSERT INTO `binlist` VALUES ('542117', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('545103', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', ' SIGNIA', '', '');
INSERT INTO `binlist` VALUES ('552645', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('552659', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('554422', '67', 'YAPI ve KREDİ BANKASI A.Ş.', 'MASTERCARD', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('427308', '71', 'FORTIS BANK A.Ş.', 'VISA', ' BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('438040', '71', 'FORTIS BANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('450918', '71', 'FORTIS BANK A.Ş.', 'VISA', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('455645', '71', 'FORTIS BANK A.Ş.', 'VISA', ' GOLD', '', '');
INSERT INTO `binlist` VALUES ('525314', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('542259', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'TITANIUM', '', '');
INSERT INTO `binlist` VALUES ('547985', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('545148', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'SIGNIA', '', '');
INSERT INTO `binlist` VALUES ('549998', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('550449', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('552207', '71', 'FORTIS BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('426391', '92', 'CITIBANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('426392', '92', 'CITIBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('450050', '92', 'CITIBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('450051', '92', 'CITIBANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('521376', '92', 'CITIBANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('544127', '92', 'CITIBANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('544445', '92', 'CITIBANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('544460', '92', 'CITIBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('547712', '92', 'CITIBANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('549220', '92', 'CITIBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('419389', '96', 'TURKISH BANK A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('518599', '96', 'TURKISH BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('529939', '96', 'TURKISH BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('552098', '96', 'TURKISH BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('400684', '99', 'ING BANK A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('408579', '99', 'ING BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('414070', '99', 'ING BANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('420322', '99', 'ING BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('420323', '99', 'ING BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('420324', '99', 'ING BANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('455571', '99', 'ING BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('480296', '99', 'ING BANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('490805', '99', 'ING BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('490806', '99', 'ING BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('490807', '99', 'ING BANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('510151', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('532443', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540024', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('540025', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('542029', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('542605', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('542965', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('542967', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('547765', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('548819', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('554297', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('554570', '99', 'ING BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('518679', '103', 'MILLENNIUM BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('534913', '103', 'MILLENNIUM BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('543624', '103', 'MILLENNIUM BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('548375', '108', 'TURKLAND BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('402277', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('402278', '111', 'FİNANS BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('402563', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('403082', '111', 'FİNANS BANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('409364', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('410147', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('413583', '111', 'FİNANS BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('414388', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('415565', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('422376', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('423277', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('423398', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('427311', '111', 'FİNANS BANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('435653', '111', 'FİNANS BANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('441007', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('444029', '111', 'FİNANS BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('499850', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('499851', '111', 'FİNANS BANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('499852', '111', 'FİNANS BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('519324', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('521022', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('521836', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('529572', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('531157', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('545120', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'SIGNIA', '', '');
INSERT INTO `binlist` VALUES ('545616', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('545847', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('547567', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('547800', '111', 'FİNANS BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('405913', '123', 'HSBC BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('405917', '123', 'HSBC BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('405918', '123', 'HSBC BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('409071', '123', 'HSBC BANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('422629', '123', 'HSBC BANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('424909', '123', 'HSBC BANK A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('428240', '123', 'HSBC BANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('496019', '123', 'HSBC BANK A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('510005', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('512651', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('519399', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('521045', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('522054', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('525413', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('525795', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('540643', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('542254', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('545183', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'SIGNIA', '', '');
INSERT INTO `binlist` VALUES ('550472', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('550473', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('552143', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('556030', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('556031', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('556033', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('556034', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('556665', '123', 'HSBC BANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('424407', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('483013', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('491373', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('491374', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('498516', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('498517', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('498518', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('498519', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('498520', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('498521', '125', 'EUROBANK TEKFEN A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('543943', '125', 'EUROBANK TEKFEN A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('543944', '125', 'EUROBANK TEKFEN A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('545863', '125', 'EUROBANK TEKFEN A.Ş.', 'MASTERCARD', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('547680', '125', 'EUROBANK TEKFEN A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('403134', '134', 'DENİZBANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('408625', '134', 'DENİZBANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('409070', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411924', '134', 'DENİZBANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('423667', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', null, 'PREPAID');
INSERT INTO `binlist` VALUES ('424360', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('424361', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('441139', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('460345', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('460347', '134', 'DENİZBANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('462276', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', null, 'PREPAID');
INSERT INTO `binlist` VALUES ('472914', '134', 'DENİZBANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('489456', '134', 'DENİZBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('510063', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('510118', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('510119', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('512017', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('512117', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('514924', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('520019', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('520303', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('543358', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('543400', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('543427', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', ' CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('546764', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('554483', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('558514', '134', 'DENİZBANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('425846', '135', 'ANADOLUBANK A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('425847', '135', 'ANADOLUBANK A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('425848', '135', 'ANADOLUBANK A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('441341', '135', 'ANADOLUBANK A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('522240', '135', 'ANADOLUBANK A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('522241', '135', 'ANADOLUBANK A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('554301', '135', 'ANADOLUBANK A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('558593', '135', 'ANADOLUBANK A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('417715', '203', 'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('432284', '203', 'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('432285', '203', 'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('534264', '203', 'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('547234', '203', 'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('548232', '203', 'ALBARAKA TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('402589', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('402590', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('402592', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('403360', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('403810', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('410555', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('410556', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('424487', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('431024', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('511660', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('512595', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('518896', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('520180', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('547564', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('525312', '205', 'KUVEYT TÜRK KATILIM BANKASI A.Ş.', 'MASTERCARD', 'MIXED PRODUCT', '', '');
INSERT INTO `binlist` VALUES ('404952', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('411685', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('428462', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('435627', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('435628', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('521848', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('537719', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('549294', '206', 'TÜRKİYE FİNANS KATILIM BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('402275', '208', 'ASYA KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('402276', '208', 'ASYA KATILIM BANKASI A.Ş.', 'VISA', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('402280', '208', 'ASYA KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('416987', '208', 'ASYA KATILIM BANKASI A.Ş.', 'VISA', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('441033', '208', 'ASYA KATILIM BANKASI A.Ş.', 'VISA', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('515849', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('524384', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'PLATINUM', '', '');
INSERT INTO `binlist` VALUES ('527585', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('529462', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', 'virtual', '');
INSERT INTO `binlist` VALUES ('531334', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'CLASSIC', '', '');
INSERT INTO `binlist` VALUES ('547799', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', '', '');
INSERT INTO `binlist` VALUES ('552529', '208', 'ASYA KATILIM BANKASI A.Ş.', 'MASTERCARD', 'BUSINESS', 'virtual', '');
INSERT INTO `binlist` VALUES ('492192', '900', 'PROVUS BİLİŞİM ', 'VISA', 'Acquiring', '', '');
INSERT INTO `binlist` VALUES ('512446', '900', 'PROVUS BİLİŞİM ', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('515865', '900', 'PROVUS BİLİŞİM ', 'MASTERCARD', 'GOLD', '', '');
INSERT INTO `binlist` VALUES ('520909', '900', 'PROVUS BİLİŞİM ', 'MASTERCARD', '', '', '');
